### ISSUE TITLE
Files with symlink in the path aren't mapped correctly

### ISSUE THREAD

**Issue by pbh20** [groboclown/p4ic4idea#156] opened 2017-08-09 21:14 UTC
I'm finding that a file such as /a/b/c/d, where b is a symlink to ../e, is being mapped to null instead of /a/e/c/d.  As a result, the file isn't being automatically checked out, and selecting "Add or edit" from the P4 menu causes an add instead of an edit.

**Comment by groboclown** [comment] 2017-08-10 04:50
Thanks for the bug report.

I have a few questions about this issue.  I'll use the file layout you described.

1. Is your IDE project root directory at `/a`, `/a/b`, or '/a/b/c` ?
2. Is your client workspace have its root at `/a/b`, `/a`, or `/a/b/c` ?

This should help me locate the various places the error could show up.  I have a feeling that this issue can show itself in more than just the add/edit action.

**Comment by pbh20** [comment] 2017-08-12 22:30
A better description of the situation is a file a/b/c/d, where c is a symlink to ../../e.  The IDE project root directory is a/b and the client workspace root is /a.

**Comment by groboclown** [comment] 2017-08-14 20:43
Thanks for the clarification.  One more thing - does the Perforce client know about a/b/c as a symlink, or does it view the those files as separately versioned, or are they ignored by the client?

I'll look into this setup and see if I can find the cause.

**Comment by pbh20** [comment] 2017-08-14 20:52
/a/b/c is checked into Perforce as a symlink.

**Comment by groboclown** [comment] 2017-08-23 18:35
I've attempted to recreate this, running on PyCharm in Linux with p4 plugin 0.9.5.  My file system setup is:

`project/` *(client root)*
` +- lib-a/a.py` *(checked into perforce)*
` +- main` *(PyCharm project root)*
` +- main/mypackage/lib-a` *(symlink to ../../lib-a, checked into Perforce as a symlink type)*

I opened `main/mypackage/lib-a/a.py` in PyCharm and edited the file.  The editor opened the file for **add**, which is the same behavior that you're describing in the bug.

But here's a strange thing.  The Perforce CLI notes that the file `main/mypackage/lib-a/a.py` is opened for add.  That means that Perforce itself isn't aware of the symlink in its internals.

The fix, as I'm seeing it, is to check if any directory in the path is a symlink, and see if that symlink is checked into Perforce as a symlink.  Just dereferencing the file to a "canonical" form could unravel too many links in a highly convoluted setup.

**Comment by groboclown** [comment] 2017-08-24 16:29
I've started a topic on the Perforce forums to see if the fine folks over there have any ideas for solving this.  The answers so far are, "If the submit fails, change it to an edit and try again," and "Tell the user how to fix the problem."  Neither of these are satisfactory.

I'm in the design phase right now.  I'm thinking of having an algorithm something like this, for files that look like they'll be opened for add (it will never look like it's already existing, so it won't show up in the "edit" list):

```java
// Have a user setting to handle this situation, because it adds extra calls to the server.
if (UserSettings.AccountForServerSymlinks) {
    List<FilePath> remainingFilesNeedingMaps = new ArrayList<>(addFiles.keys());
    Map<FilePath, String> currentKnownDepotPaths = new HashMap<>(addFiles);
    Map<FilePath, String> symlinkedRealDepotPath = new HashMap<>();

    // There may be multiple symlinks pointing to symlinks, so we need to loop until we've
    // exhausted the list of files that have symlinks.
    do {
        // Find the complete list of parent directories for the requested files for add, up to but not including
        // the depot.  So, a file like //depot/a/b/c.txt would have //depot/a, //depot/a/b as the returned list.
        splitParents = splitParentPathsFor(remainingFilesNeedingMaps);

        // Run p4 fstat "-F "headType = symlink" (split parents list)
        // Returns only the paths that are symlinks.
        linkParentFiles = getSymlinkFileStats(splitParents);

        Map<FilePath, String> foundSymlinks = new HashMap<>();
        for (parentSymlink: linkParentFiles) {
            // We need to download (!) the contents of the symlink to see where it points.
            linksToPath = getContentsFor(parentSymlink);

            // The complicated logic: find the files in the remainingFilesNeedingMaps list
            // whose contents have the symlink as a parent.  Change the symlink to the
            // mapped-to link, put that mapping into the foundSymlinks,
            // and remove that file from the remainingFilesNeedingMaps list.
            // The currentKnownDepotPaths map probably needs to be updated, too.
            mapParentForRemaining(remainingFilesNeedingMaps, parentSymlink, linksToPath, currentKnownDepotPaths, foundSymlinks);
        }
        // Everything left in the remainingFilesNeedingMaps are files that don't have a symlink,
        // so we can ignore those.
        remainingFilesNeedingMaps.clear();
        // However, those that *were* mapped may have further symlinks.
        remainingFilesNeedingMaps.addAll(foundSymlinks.keys());
        // And update our list of files symlinked
        symlinkedRealDepotPath.putAll(foundSymlinks);

    // Keep repeating until there aren't any more discovered symlinked parents.
    } while (! linkParentFiles.isEmpty());

    // Each file that was marked as being in a symlink path will need to be calculated for
    // add or edit based on the resolved path.
    updateAddEditLists(addList, editList, symlinkedRealDepotPath);
}

// Perform the usual add / edit actions
```

**Comment by groboclown** [comment] 2017-09-14 18:54
I have a beta version of the plugin with a fix to address this issue.

https://github.com/groboclown/p4ic4idea/releases/tag/untagged-0a97f5dc91f26c53afa9

Would you please try out this version and let me know if it can handle this situation better?

**Comment by pbh20** [comment] 2017-09-15 20:16
Thanks! I'll try it out and let you know how it goes.

**Comment by groboclown** [comment] 2018-10-26 17:44
Marking as closed.

**Closed by groboclown** 2018-10-26 17:44 UTC
Labels: bug
