### ISSUE TITLE
Repository view doesn't work

### ISSUE THREAD

**Issue by scriptacus** [groboclown/p4ic4idea#77] opened 2015-11-17 21:55 UTC
IDEA 15.0.1 with 0.7-RC4

The Repository section of Version Control is blank... it just has the empty windows with "Press Refresh button to load repository changes".  Pressing the Refresh button just brings up the "VCS History Cache Settings" dialog.   When I click "OK", I can see a few milliseconds of updating on the status bar (so quick I can't read it) and then nothing.

**Comment by groboclown** [comment] 2015-11-17 22:13
Thanks for the bug report.  Unfortunately, this is a known limitation with the current issue, and there's an existing feature request to implement this part of the API.

Closing this off as a duplicate of #73.

**Closed** 2015-11-17 22:14 UTC
Labels: duplicate
