### ISSUE TITLE
SSL Connection Doesn't work at all

### ISSUE THREAD

**Issue by stardust85** [groboclown/p4ic4idea#133] opened 2016-09-19 14:02 UTC
OS: Oracle Linux 6.7
java: Oracle JDK 1.8.92
plugin version: 0.7.18
1. In Settings -> Version Control -> Perforce, I fill authorization via Client password and press Check Connection. I get "Your connection information works fine.". I select my workspace and press OK.
2. Restart Idea (just to be sure) - not needed to reproduce
3. View -> Tool Windows. Version Controls is grayed out. Editting a file doesn't offer to check it out from perforce.

**Comment by stardust85** [comment] 2016-09-21 09:45
I should mention that we use ssl on our perforce server.

**Comment by stardust85** [comment] 2016-09-21 10:11
I downloaded Ultimate Edition, removed official perforce plugin and installed this plugin again. I got this error: 

```The Perforce server has a SSL fingerprint that does not match the one you specified (null).  Error occurred during the SSL handshake: invalid SSL session```

I modified idea.sh to set JAVA_HOME to a java which has jce. It didn't help.

**Comment by groboclown** [comment] 2016-09-22 18:52
So, you're correctly running with a jce-enabled Java, that's good.

It looks like you need to set the SSL fingerprint in the setup.  If you use the "Client Password" connection, you'll have a field in which you can set the SSL Trust Fingerprint.  Have you set that to the server's fingerprint?

**Comment by stardust85** [comment] 2016-09-22 19:16
No, jce-enabled java did not do any change. I used p4config file and I see it in the Environment variables window when I press Reload environment variables.

**Comment by groboclown** [comment] 2016-09-22 19:42
For the config file, the only support for the SSL fingerprint is by pointing the P4TRUST value in your config file to the ssl trust file.  That trust file is maintained by your native P4 client.

**Comment by dilip-rai** [comment] 2016-09-23 10:32
Looks like an injection. It used to work before with ssl.

**Comment by groboclown** [comment] 2016-10-11 16:05
Are you still seeing an issue with this?

**Comment by stardust85** [comment] 2016-10-11 16:29
Did you release a new version, which I should try?

**Comment by groboclown** [comment] 2016-10-24 01:27
I just put out a new release, but I don't think this will explicitly solve your problem.  I haven't been able to reproduce this issue locally, so unfortunately I can't provide suggestions for additional courses of action other than using the command-line "p4 trust".

**Comment by rajeshwarig** [comment] 2016-10-27 17:20
I tried using the "Specific Config file" as well as "Client password" options with the correct SSL fingerprint (that was printed when I ran "p4 trust -l" but I'm still getting the error "the Perforce server has a SSL fingerprint that does not match the one you specified. Error occurred during ssl handshake: invalid ssl session". The error message also contains the SSL fingerprint it seems to have tried and it is correct! Please help!

**Comment by groboclown** [comment] 2016-10-28 13:16
Maybe you're running in an environmthe client. that I haven't been able to sufficiently replicate.  I don't know if there is something extra in your local computer that we haven't tracked down, or if your server has a different security setup than what the plugin supports.

Here's how I just tested it out:

1. I created a new p4d server.  I created the certificates (`p4d -Gc`) and started it as `p4d -v 3 -p ssl:1666`  The `-v 3` is just for debugging.  This is using p4d version LINUX26X86_64/2015.2/1436535.
2. On my Windows client, I set the P4PORT env value to ssl:p4dhost:1666, trusted the server (`p4 trust`), created a new user (`p4 user user1`), set a password (`p4 passwd`), created a client (`p4 client`).
3. Also on my Windows client, I started IntelliJ, created a new project, whose root directory was in the newly created client's root directory.
4. In IntelliJ, I configured the plugin connection with Client Password, port ssl:p4dhost:1666, User user, and the 20 hex byte pairs for the trust fingerprint.

The plugin asked for my password, then was able to connect to the server and discover the clients.  I was then able to add and commit a file

The only other things that could be going on that I can think of is an authentication issue masked as an SSL problem, or perhaps your p4trust directory on your CLI client is different.

**Comment by dilip-rai** [comment] 2016-11-03 07:50
OK finally I got it it working :), for some reason the plugin was using JRE bundled with Android Studio. All I had to do is copy JCE libraries to JRE bundled with Android Studio. 
Please note that I had JCE libraries copied to my default JDK (JAVA_HOME points to it and I have added it to path). It was working with older version of Android Studio with older version of P4 plugin. Probably, something has changed in the way JRE is picked by plugin.
Hope it ill help others!

**Comment by groboclown** [comment] 2016-11-03 15:44
If the plugin does not find the JCE libraries, it is supposed to report an error, with a description of the java location and version you're using.  Were you not seeing this message?  If the message you were seeing was mismatched SSL fingerprint, then I can augment the error message to include the java version information, along with guidance to check the JCE library.

**Comment by dilip-rai** [comment] 2016-11-04 03:43
Thanks for investigating the issue and quick response.

The error message complained about mismatched SSL fingerprinrt only. There
was no information on JRE location or JCE library.
It would be great to have correct info in error message.

**Comment by kams-mash** [comment] 2016-11-08 00:14
@dilip-rai - Thanks! your suggestion worked for me. 

(After installing JCE) I Copied all the files from "JAVA_HOME/jre/lib/security" to "android-studio/jre/jre/lib/security"

**Comment by groboclown** [comment] 2017-02-20 23:43
Fixed in 0.8.0

**Closed by groboclown** 2017-02-20 23:43 UTC
Labels: bug
