### ISSUE TITLE
Files reverting, not initiated by user

### ISSUE THREAD

**Issue by scriptacus** [groboclown/p4ic4idea#181] opened 2018-11-10 17:01 UTC
One of my coworkers has been trying the new plugin, but mentioned that multiple times he’s had files disappear from his changelists.  In these cases he’s been fortunate enough to have work saved by IntelliJ Local History.  We’re not entirely positive it’s the 2017 version of the plugin that causes it, but he downloaded the IntelliJ Ultimate trial and started using their plugin instead.  The issue has not occurred since (about 1 week).

**Comment by groboclown** [comment] 2018-11-12 16:50
One consistent bug has been the intermediary state between an action occurring and a forced refresh on the UI, where it looks like the file isn't checked out anymore.  However, this is vastly different than an actual revert on P4.

There are several places where a revert can happen (all take place in the `ConnectCommandRunner` class):
1. An explicit request to revert a file.
2. Request to add or edit a file when it's deleted on the server; the delete is reverted.
3. Request to delete a file when it's open for add or edit on the server; the add or edit is reverted.
4. Request to move a file when the source is open for add or delete; the source is reverted.
5. Request to move a file when the source is open for add or not on the server, and the target is open for delete; the target is reverted.
6. Request to move a file when the source is known by the server and the target is open for add, edit, or delete; the target is reverted.

Step 6 has some situations that need refinement, but the core revert logic will need to be performed.

All of these situations require an accurate status from the Perforce server, and a quick review of the logic shows that they poll the server directly before performing logic, rather than relying upon the local cache.

I'll revisit this logic to see if there are other file situations that might cause an incorrect revert.  One area might be for multiple-file operations.

**Comment by groboclown** [comment] 2018-11-27 19:18
The use cases I've walked through haven't revealed any unexpected reverts.  However, I discovered another issue related to this, #184, that puts the local and P4 marked files in a bad state.

**Comment by groboclown** [comment] 2018-11-29 17:06
I'm knocking this down from blocker because I haven't been able to reproduce this issue.  I added additional code and logging around this area to help identify possible issues if they are seen again.  I'll keep this open for a while, though, because I cannot say whether it has been fixed.

**Comment by staffanf** [comment] 2019-01-17 14:04
Several people at our workplace has encountered this bug when using this plugin.
We format code outside of IntelliJ from our command line builds and after they go back to IntelliJ their changes are reverted.
It is really annoying and for those using it is a blocker. The version they are using is 0.10.2.
It did not seem to be in the pre 0.10 versions.

**Comment by groboclown** [comment] 2019-01-18 16:09
I suspect this issue appears in these situations:
1. A file is open for delete (not on disk, and the changelist isn't submitted), then a new file is created over the old one.  The plugin will revert the delete operation so that it can perform an edit.  However, the revert operation incorrectly restores the original value.
2. The target for a move operation was marked for delete or edit.  Behavior similar to to above happens.

I'm adding fixes to make the revert in these situations not touch the existing file in these situations.

Additionally, I've added a new user option to display to the user when reverts happen, along with a detailed message describing why the revert happened.  Hopefully this will make error reporting for this issue easier.

**Comment by groboclown** [comment] 2019-01-18 18:48
New version is available (0.10.3) with a fix for this.  Additionally, if you still see issues with reverting, you can select the option "Show notification when reverts happen" under the **Settings** -> **Version Control** -> **Perforce** dialog; this will show a notification with the reverted files and why they were reverted.

**Comment by groboclown** [comment] 2019-01-23 17:48
I'm closing this off based on no additional feedback.  If this ends up still being an issue, please reopen it or create a new ticket.

**Comment by AndyCaley** [comment] 2019-05-02 16:27
I'm using plug-in version v0.10.6 with intellij 2019.1.1 and am seeing these random reverts quite often.  I started noticing them the last time I upgraded the perforce plugin but I don't remember what version I used to have.  I can't figure out what is causing them, I do have the logging enabled and this is what is output:

2:43 PM	Reverted [D:/p4/near_acaley_secondary/gradle/common/libraries-internal.gradle]: Reverted `[D:/p4/near_acaley_secondary/gradle/common/libraries-internal.gradle]` due to User request to revert files; on-disk contents changed.

2:48 PM	Reverted [D:/p4/near_acaley_secondary/gradle/common/libraries-internal.gradle]: Reverted `[D:/p4/near_acaley_secondary/gradle/common/libraries-internal.gradle]` due to User request to revert files; on-disk contents changed.

4:22 PM	Reverted [D:/p4/near_acaley_secondary/workgroup/src/silos/tableau-server/services/war-vizportal/src/com/tableausoftware/grpc/DatasourceGrpcService.java]: Reverted `[D:/p4/near_acaley_secondary/workgroup/src/silos/tableau-server/services/war-vizportal/src/com/tableausoftware/grpc/DatasourceGrpcService.java]` due to User request to revert files; on-disk contents changed.

**Comment by groboclown** [comment] 2019-05-07 12:54
It looks like the "on-disk contents changed" could be the trigger that's causing this problem.  I'm still digging into it.

**Comment by groboclown** [comment] 2019-05-07 16:15
There's a bug on the command "revert unchanged" where it was reverting all opened files, which is a really big bug that needs fixing.

However, investigation shows that these rollback events are only triggered when the IDE sends a request to the [`RollbackEnvironment`](http://git.jetbrains.org/?p=idea/community.git;a=blob;f=platform/vcs-api/src/com/intellij/openapi/vcs/rollback/RollbackEnvironment.java;h=2480d40faafbf78448d1ff99748431333a711adb;hb=HEAD) implementation, specifically to the `rollbackChanges` and `rollbackIfUnchanged` methods; the other rollback methods invoke a forceSync.

My guess is that, due to the bug with the unchanged implementation, the IDE may be sending unexpected `rollbackIfUnchanged` calls.

I've added `info` level logging to the rollback environment implementation class, and fixed that bug around the unchanged flag.  The logs will be sent to the IDE log (found under *Help* -> *Show Log In Explorer* for Windows users).

**Comment by groboclown** [comment] 2019-05-07 16:46
v0.10.7 (just released) has the fix + logging improvements.

**Comment by groboclown** [comment] 2019-07-24 15:55
Have these issues still happening?

**Comment by scriptacus** [comment] 2019-07-26 15:37
Can't say at this point, as we've internally switched to using the Ultimate edition which contains the official Perforce plugin.

**Comment by groboclown** [comment] 2019-08-01 13:58
Closing due to no more reported issues.  If this shows up again, please open a new ticket.

**Closed by groboclown** 2019-08-01 13:58 UTC
Labels: Requesting Feedback, blocker, bug
