### ISSUE TITLE
Changing working directory for project from P4V breaks p4ic4idea plugin

### ISSUE THREAD

**Issue by rfsheffer** [groboclown/p4ic4idea#84] opened 2015-12-09 02:41 UTC
If you have a fully configured and working p4ic4idea plugin and change the working directory in perforce, and copy all the files to the new folder, once you reopen android studio the perforce plugin will no longer understand your perforce workspace.

Error message: Your Perforce client has root directories [E:\Perforce\[workspacename]], but your project is configured with VCS directories [gradle].  You need to update or refresh your Perforce settings in order to correct this issue.

Pycharms perforce plugin created by intelliJ works fine, so there must be a problem with this plugin.

**Comment by groboclown** [comment] 2015-12-09 02:52
Thanks for the bug report.

Let me see if I can follow your steps.  When you say that you change "the working directory in Perforce," do you mean that you change the root directory of the workspace?

**Comment by rfsheffer** [comment] 2015-12-09 03:20
Oh sorry, yep I mean the Workspace root. I had to reduce it because my file paths were getting too long for windows. I changed the workspace root in P4V, closed P4V, moved the folders to match the new root, and re-opened P4V. Everything was fine in perforce, but now I am getting this error in Android Studio. Somewhere the old root path is being saved. I checked the registry and couldn't find anything. P4V and p4 cmd both say the root is correct.

Thanks for the quick reply :)

**Comment by groboclown** [comment] 2015-12-09 03:28
I just happened to be looking at the issues just after you posted the bug :)

I think I know where the issue is in the code, but for a quick work-around, you can first close Android Studio, then look in your Android Studio config folder - on Windows, it's stored by default under your User folder, in `.AndroidStudio`.  Open the file `config/options/perforce.xml`, and search for your root directory path.  It should be under a `<server ...><workspace ...><r p="directory"/>` tag.

Essentially, the workspace root is cached, and is not being correctly reloaded when you reopened Android Studio.

**Comment by rfsheffer** [comment] 2015-12-09 03:42
Thanks for the help, it worked! I can perforce again!
I ended up just trashing that file and letting it get regenerated, which it did.

Cheers, thanks for the awesome plugin. :)

**Comment by groboclown** [comment] 2015-12-09 18:38
It looks like I have a fix for this, that dovetailed in nicely with another bug fix.  I changed my cached workspace directory, and started up Android.  The plugin picked up the correct workspace and it didn't complain.  Let me know if you see this again after the 0.7.2 release.

**Closed by groboclown** 2015-12-09 18:38 UTC
Labels: bug
