### ISSUE TITLE
Setting up SSL fails match

### ISSUE THREAD

**Issue by glaw** [groboclown/p4ic4idea#145] opened 2017-03-13 16:37 UTC
Despite entering valid ssl fingerprint, error pop up appears

"Unexpected problem: The Perforce server has a SSL fingerprint that does not match the one you specified (null). Error occurred during the SSL handshake: invalid SSL session"

This is seen 0.6.0 (IDEA 2015) and 0.83.0 (IDEA 2016.3.4)

**Comment by groboclown** [comment] 2017-03-14 02:09
This might be related to the issue around not having the Java encryption extensions (JCE) installed (see #133).  If you don't have them already installed, please try installing them and see if you're still experiencing the same issue.

**Comment by yuehann** [comment] 2017-03-14 12:43
hi,

I'm having the same issue, and I have JCE libraries installed.

thx,

**Comment by yuehann** [comment] 2017-03-14 15:26
Hi,

Sorry, It was my mistake. I was putting the JCE libraries in my Java installation and not in the one that comes with PyCharm (C:\Program Files\PyCharm Community Edition 2016.3.2\jre\jre\lib\security)

Hope it helps,
Cheers

**Comment by glaw** [comment] 2017-03-15 16:09
The JCE libraries have been installed.  They were put in the proper location also.  Across the organization sometimes it was fixable by removing the p4trust file and restarting IDEA.  In at least one instance, maybe two this did not fix the issue.

**Comment by sephiroth74** [comment] 2017-03-17 17:11
I can confirm that manually deleting .p4trust and restarting IDEA fixed the issue.

**Comment by jimkeir** [comment] 2017-04-04 19:12
Same issue here. Installing JCE allowed me to connect, but there are several other issues.

- The UI shows "Server Fingerprint" always empty, and as "(no value)" under Resolved Properties, no matter how many times I enter it. The connection does go through, as long as I specify a trust file and have already logged in with P4V.
- I must add the "Properties" section and manually specify P4PORT and P4USER, even though they're defined using "p4 set" and I have included the "Environment Properties" section.
- The "Properties" section has no override for "P4PASSWD", even though the "Require a Password" section is included. I have to log in manually on the command line to create a p4ticket.txt file.
- There seems to be a circular dependency on the "Select Client" section. With this field empty, "Refresh Client List" does nothing. Clicking the "Refresh" button in the bottom section shows three identical errors "No client name in configuration". I have to enter something in the "Client:" field before either Refresh option does anything. Even then, the client list often does not refresh even though the server logs are showing that the list was returned correctly. And it would be nice if the list was shown in alphabetical order ;)
- The values of "P4TICKET", "P4TRUST" and "P4LOGINSSO" in the "Properties" section are (inappropriately) set to the project's root directory. However, regardless of the settings here, the "Resolved Properties" tab shows the correct values of <UserDir>\p4tickets.txt and <UserDir>\p4trust.txt  Note that the variable shown under "Resolved Properties" is P4TICKETS, while the label for the value under "Properties" is "P4TICKET".
- Going back into settings clears the Client name, and it will again not attempt to communicate with the server unless I type some random stuff into the Client textbox first.
- After all this, closing the Settings dialog shows an immediate error "P4ServerName object already checked out by Thread[ApplicationImpl pooled thread 16,4,main], giving me the choice to retry configuration or work offline. Completely removing the plugin and reinstalling did fix this one, but all the other issues remain.

This all worked just fine when the server didn't require SSL.

Version 0.8.3 .

**Comment by groboclown** [comment] 2017-04-17 21:37
Version 0.8.4 is out with some fixes to these issues.  However, the primary issue is still present.

@jimkeir Thanks for reporting on these issues.  I'll look into each one and open a new issue if it looks like it's still present.

**Comment by groboclown** [comment] 2017-04-21 14:15
This should be fixed now in 0.8.5.  Please let me know if you're seeing other issues, or if this doesn't fix it for you.

**Closed by groboclown** 2017-04-21 14:15 UTC
Labels: bug
