### ISSUE TITLE
Can't change Root Directory

### ISSUE THREAD

**Issue by TheAndrewStevens** [groboclown/p4ic4idea#148] opened 2017-05-11 15:44 UTC
I can't change the Root dir option in the drop down section under the "Server Connection" tab from the project root, even after trying all combination of login options, including specifying only a p4 config file in C:/ and selecting just a Directory (C:/) in the "Version Control" options (instead of the default <Project>).
The vast majority of my project source files are native (cpp/h) files that exist outside (above) the Android Studio root directory. Presumably because I can't change the root directory I can't check out the vast majority of files in my project making the plugin essentially useless.
NOTE: This was working in the previous version (0.85 I think...)

**Comment by groboclown** [comment] 2017-05-11 18:13
Just to be clear, your Android project root is, say, "c:/a/b/c", your client workspace root is "c:/a", and you want to check out files from anywhere outside the project root?  There was a change to this in the latest release, yes.

**Comment by groboclown** [comment] 2017-05-11 19:39
And you would prefer the old behavior of being able to work with files outside the project root directory.  Gotcha.  This should be straight forward to change.

**Comment by TheAndrewStevens** [comment] 2017-05-12 08:08
Spot on, yes. Thanks!

**Comment by groboclown** [comment] 2017-05-12 18:06
Fix is checked in.

**Comment by johnchanwork** [comment] 2017-05-18 00:29
I'm on 0.8.7 (latest) and still have this issue. The root dir is hardcoded to the project root and I can't change it to the workspace root. I tried both install from JetBrain and download from github's release and installed from disk. Could you double check please?

**Comment by TheAndrewStevens** [comment] 2017-05-18 08:51
I also had a few issues getting it working with 0.8.7 but managed to get around them by fiddling with a few settings. In Settings->Version Control I had to remove the "Project" perforce entry and just have the root directory entry. I also had to run File->Invalidate Caches/Restart..

**Comment by groboclown** [comment] 2017-05-18 16:31
I'll re-examine the code.  But I want to better understand what you did here.  I think this is what you are saying you had.

1. You initially had the "Perforce" VCS assigned to the default `<Project>` directory.  This caused the issue of the Perforce plugin to not scan outside the project.
2. You removed the `<Project>` directory, and added the client workspace's root directory (which is a parent of `<Project>`) to the VCS list.
3. You ran the invalidate caches and restarted.

This does make sense.  The IDE is setup to allow different VCS providers to have different roots in the same project.  So, as a VCS integration provider, the plugin needs to be root aware, and not try to step in other locations.

It looks like your solution is the proper one.

**Comment by groboclown** [comment] 2017-06-02 18:07
The latest version might fix this.  The fix is where you have a p4 config file at an ancestor level than the project root.  The fix is also if you have multiple config files; the regression prevented the ancestor config from being used by the child.

**Comment by TheAndrewStevens** [comment] 2017-06-05 14:49
Unfortunately, the latest version (0.9.0) seems to have broken this again. To recap my settings:

- Settings->Version Control: 1 entry ( Directory: C:\Dir1, VSC: Perforce)
- Settings->Version Control->Perforce->Connection Properties (Specific Configuration File: C:\Dir1\p4.p4config, Select Client, Properties)

Settings->Version Control->Perforce->Server Connection (Root dir: C:\Dir1\Dir2\Project Directory\ is the only option)

My Perforce workspace root is set to C:\Dir1 but I can't select this directory from the Server Connection tab in the perforce settings.

**Comment by groboclown** [comment] 2017-06-08 15:57
Nuts!  It seems like my efforts to fix this just end up fighting your work-arounds.

I'll see what I can do to get you past this.  From what I can tell now, it seems like the issue is the plugin doesn't search down to the client root.

The Server Connection root selection dialog is supposed to show the directories that define a configuration.  If you create a file configuration at that c:\dir1 level, then it should show up as a root.  I'll see about allowing the client root to be the base directory.  Unfortunately, though, Windows Perforce clients allow a "null" root (to allow a drive-spanning client view), which might be troublesome.

**Comment by groboclown** [comment] 2017-06-09 13:51
I've been rereading this issue several times to get a really good grasp of the use case.  I keep thinking that I understand it, but then I get distracted.

I think the use case is simply, "I want to manage Perforce files with the plugin that are outside the project root."

This bug stems from a combination of several issues.

1. The JetBrains changelist view limits what files it includes to just those under VCS roots.  This means that, in order for an edited file to show up in the changelist view, you need to modify your VCS root path to be at the higher directory level.
2. The plugin matches affected files on your computer to a Perforce client/server based on the "root dir" of the configurations.
3. Only exact file-based configuration setups ("File" and "Environment", when the environment contains a `P4ENVIRO` or an absolute `P4CONFIG` file path) currently allow their "root dir" to be outside the project root.  The relative file configuration can be at a different directory level, but it will only be at a child directory.

I think the "right" fix here would change the configuration's default root dir value to instead use the VCS roots.  This will change some of the implementation details, but seems like the more appropriate path.  Unfortunately, it would mean a configuration alteration when the VCS roots change, but I think that's a minor tradeoff, as it's an infrequent operation.  (*Note for Future Me*: looks like add an event bus listener for `ProjectLevelVcsManager.VCS_CONFIGURATION_CHANGED` method `directoryMappingChanged()`)

A possible work-around is to use a configuration file that's at the higher level, and also set the VCS root to that directory.

**Comment by groboclown** [comment] 2017-06-21 16:13
The 0.9.2 release *should* better handle having VCS roots at higher levels than the project root.  The logic is little complicated: it creates the minimal set of the project root, the VCS roots, and the configuration path (the only config stack settings that support the path are "file" and "relative file").

I've tested this out with projects that have:

* VCS root at the project level, with one module.
* VCS root at the project level, with multiple modules.  This makes VCS roots one per module, but if the modules are below the project root, the project root will be used instead.
* Multiple VCS roots, some outside the project.  The roots outside the project will show up as separate paths.

**Comment by TheAndrewStevens** [comment] 2017-06-27 10:57
Thought I'd let you know that 0.9.2 has fixed my issue with external root directories - thanks!

**Comment by groboclown** [comment] 2017-06-29 21:01
Thanks for reporting back!  Glad I could finally resolve this one.

**Closed by groboclown** 2017-06-29 21:01 UTC
Labels: bug
